# Generated by Django 3.1.7 on 2021-03-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0002_auto_20210323_0942'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=200)),
                ('permission', models.IntegerField(default=0)),
                ('application', models.ForeignKey(help_text='Name of the service registered in auth service', on_delete=django.db.models.deletion.CASCADE, related_name='auth_permissions', to='provider.application')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_permissions', to='auth.group')),
            ],
            options={
                'db_table': 'application_view_group_permission',
            },
        ),
    ]
