# Generated by Django 3.1.7 on 2021-03-23 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='response_type',
            field=models.CharField(blank=True, choices=[('code', 'Authorization code')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scopes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skip_authorization',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope', models.TextField(blank=True, null=True)),
                ('redirect_uris', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('challenge', models.CharField(max_length=128)),
                ('challenge_method', models.CharField(choices=[('plain', 'plain'), ('S256', 'S256')], max_length=6)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
