# Generated by Django 3.1.7 on 2021-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_application_application_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_uri',
            field=models.TextField(blank=True, help_text='URL of the application; include port number if application is IP hosted', unique=True),
        ),
    ]
