# Generated by Django 3.1.7 on 2021-04-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20210401_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_uri',
            field=models.TextField(blank=True, help_text='URL of the application. Include port number if application is IP hosted. Format: (www.domain.com, 127.0.0.1:8000)', unique=True),
        ),
    ]
