# Generated by Django 3.1.7 on 2021-05-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20210413_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='idtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idtoken',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
