# Generated by Django 3.1.7 on 2021-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20210517_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
