# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/verification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/verification.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19protos/verification.proto\"\'\n\x15TokenValidatorRequest\x12\x0e\n\x06\x62\x65\x61rer\x18\x01 \x01(\t\"6\n\x16TokenValidatorResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32J\n\x04\x41uth\x12\x42\n\rValidateToken\x12\x16.TokenValidatorRequest\x1a\x17.TokenValidatorResponse\"\x00\x62\x06proto3'
)




_TOKENVALIDATORREQUEST = _descriptor.Descriptor(
  name='TokenValidatorRequest',
  full_name='TokenValidatorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bearer', full_name='TokenValidatorRequest.bearer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=68,
)


_TOKENVALIDATORRESPONSE = _descriptor.Descriptor(
  name='TokenValidatorResponse',
  full_name='TokenValidatorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='TokenValidatorResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='TokenValidatorResponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['TokenValidatorRequest'] = _TOKENVALIDATORREQUEST
DESCRIPTOR.message_types_by_name['TokenValidatorResponse'] = _TOKENVALIDATORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenValidatorRequest = _reflection.GeneratedProtocolMessageType('TokenValidatorRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOKENVALIDATORREQUEST,
  '__module__' : 'protos.verification_pb2'
  # @@protoc_insertion_point(class_scope:TokenValidatorRequest)
  })
_sym_db.RegisterMessage(TokenValidatorRequest)

TokenValidatorResponse = _reflection.GeneratedProtocolMessageType('TokenValidatorResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOKENVALIDATORRESPONSE,
  '__module__' : 'protos.verification_pb2'
  # @@protoc_insertion_point(class_scope:TokenValidatorResponse)
  })
_sym_db.RegisterMessage(TokenValidatorResponse)



_AUTH = _descriptor.ServiceDescriptor(
  name='Auth',
  full_name='Auth',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=126,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='ValidateToken',
    full_name='Auth.ValidateToken',
    index=0,
    containing_service=None,
    input_type=_TOKENVALIDATORREQUEST,
    output_type=_TOKENVALIDATORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTH)

DESCRIPTOR.services_by_name['Auth'] = _AUTH

# @@protoc_insertion_point(module_scope)
